orders/urls.py
from django.urls import path
from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrdersShowView, OrderShowView

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/', OrdersShowView.as_view(), name='orders'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order-canceled/', CanceledTemplateView.as_view(), name='order_canceled'),
    path('order/<int:pk>/', OrderShowView.as_view(), name='order_detail'),]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.cache import cache_page

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cache_page(600)(IndexView.as_view()), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from users.models import User
import json  

class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
            (CREATED, 'Создан'),
            (PAID, 'Оплачен'),
            (ON_WAY, 'В пути'),
            (DELIVERED, 'Доставлен'))

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def get_total_cost(self):
        try:
            basket_items = json.loads(self.baskets)
            if not isinstance(basket_items, list):
                raise ValueError("basket_items is not a list")
        except json.JSONDecodeError:
            raise ValueError("baskets contains invalid JSON")

        total_cost = 0
        for item in basket_items:
            if not isinstance(item, dict):
                raise ValueError("Each item in basket_items should be a dictionary")
            total_cost += float(item['fields']['price']) * item['fields']['quantity']  # Преобразование цены в float
        return total_cost

    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'
    

orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Иван'}))
    last_name = forms.CharField(widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Иванов'}))
    email = forms.EmailInput(
            attrs={
                'class': 'form-control', 
                'placeholder': 'you@email.com'})
    address = forms.CharField(widget=forms.TextInput(
            attrs={
                'class': 'form-control', 
                'placeholder': 'Россия, Москва, ул. Мира, дом 6'}))
    basket_history = forms.JSONField()

            
    class Meta:
        model = Order
        fields = (
                'first_name', 'last_name',
                'email', 'address', 'basket_history')

orders/views.py
import json
import uuid

from django.views.generic import DetailView
from yookassa import Configuration, Payment
from http import HTTPStatus

from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from common.views import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from django import template
from datetime import datetime
import pdb;

from products.models import Basket


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'Алькир - Спасибо за заказ!'


class CanceledTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/canceled.html'


class OrderCreateView(TitleMixin, CreateView):
    title = 'Алькир - Оформление заказа'
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.form_valid(form)

            Configuration.account_id = settings.ACCOUNT_ID
            Configuration.secret_key = settings.SECRET_KEY

            # Подготовка данных платежа
            order_total = self.order.get_total_cost()  # Предположим, что у заказа есть метод для расчета общей стоимости
            payment = Payment.create({
                'amount': {
                    'value': str(order_total),  # общая стоимость заказа
                    'currency': 'RUB'
                },
                'confirmation': {
                    'type': 'redirect',
                    'return_url': '{}{}'.format(settings.DOMAIN_NAME, reverse("orders:order_success"))
                },
                'capture': True,
                'description': f'Заказ номер {self.order.id} от {datetime.now().strftime('%d/%m/%Y')}'
                # Используем ID заказа
            }, uuid.uuid4())
            self.order.status = Order.PAID
            self.order.save()
            return HttpResponseRedirect(payment.confirmation.confirmation_url, status=HTTPStatus.SEE_OTHER)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        basket_history = self.request.POST.getlist('basket_history')

        # Ожидаем один элемент в basket_history, который является строкой JSON-массива
        if len(basket_history) != 1:
            raise ValueError("basket_history must contain exactly one JSON array string")

        try:
            baskets = json.loads(basket_history[0])  # Десериализация JSON массива
            if not isinstance(baskets, list):
                raise ValueError("basket_history does not contain a JSON array")
        except json.JSONDecodeError:
            raise ValueError("Invalid JSON in basket_history")

        # Проверка, что каждый элемент массива является словарем
        for item in baskets:
            if not isinstance(item, dict):
                raise ValueError("Each item in basket_history must be a dictionary")


        form.instance.baskets = json.dumps(baskets)  # Сериализация обратно в JSON строку
        response = super(OrderCreateView, self).form_valid(form)
        Basket.objects.filter(user=self.request.user).delete()
        self.order = form.instance  # Сохраняем объект заказа
        return response


class OrdersShowView(TitleMixin, ListView):
    model = Order
    title = "Алькир - заказы"
    template_name = 'orders/orders.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:orders')

    def get_queryset(self):
        user_id = self.request.user.id
        return Order.objects.filter(initiator_id=user_id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OrdersShowView, self).get_context_data()
        return context


class OrderShowView(TitleMixin, DetailView):
    title = "Алькир - заказ"
    template_name = 'orders/order.html'
    model = Order
    context_object_name = 'order'
    success_url = reverse_lazy('orders:order_detail')

orders/templates/orders/canceled.html
<!DOCTYPE html>
<html>
	<head>
		<title>Checkout canceled</title>
	</head>
	<body>
		<h1>Checkout canceled</h1>
	</body>
</html>

orders/templates/orders/order-create.html
{% extends 'products/base.html' %}
{% load custom_filters %}
{% load static %}

<script src="{% static 'vendor/js/basket.js' %}"></script>

{% block content %}
<!-- Page Content -->
<section>
    <div class="alert alert-warning text-center" role="alert">
        Пожалуйста, заполните адрес электронной почты.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Оформление заказа</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Корзина</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                    <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ basket.product.name }}</h6>
                            <small class="text-muted">{{ basket.quantity }} шт.</small>
                        </div>
                        <span class="text-muted">{{ basket.sum }} руб.</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Сумма к оплате</span>
                        <strong>{{ baskets.total_sum }} руб.</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Адрес доставки</h4>
                <form action="{% url 'orders:order_create' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Адрес</label>
                            {{ form.address }}
                        </div>
                        <input type="hidden" name="basket_history" value="{{ baskets|jsonify_baskets }}">

                    </div>

                    <hr class="my-4">

                    <button id="continue-button" class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/order.html
{% extends 'products/base.html' %}
{% load custom_filters %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ № {{order.id}}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in order.basket_history %}
                    <tr>
                        <th scope="row">
                            {{item.fields.name}}
                        </th>
                        <td>{{item.fields.quantity}}</td>
                        <td>{{item.fields.price|to_float}} руб.</td>
                        <td>{{ item.fields.quantity|multiply:item.fields.price }} руб.</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого: {{order.basket_history|get_total_sum|to_float_td}} руб.</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/orders.html
{% extends 'products/base.html' %}
{% load custom_filters %}

{% block content %}
<!-- Page Content -->
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказы</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Создан</th>
                        <th scope="col">Итого</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>
                    {% for order in object_list  %}
                    <tr class="{% if order.status == 0 %} table-warning {% elif order.status == 1 %} table-primary {% elif order.status == 2 %} table-info {% else %} table-success {% endif %}">
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.created }}</td>
                        <td>{{order.basket_history|get_total_sum|to_float_td}}</td>
                        <td>
                            <a href="{% url 'orders:order_detail' order.id %}">просмотреть</a>
                        </td>
                    </tr>
                    {% empty %}
                    <h3>Список заказов пуст</h3>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header">
                        <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                    </div>
                    <div class="card-body text-center">
                        <h4>
                            Ваш заказ успешно сформирован.
                        </h4>
                        <a class="btn btn-primary btn-lg mt-4 float-center" href="{% url 'products:index' %}">
                            На главную
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}